# Tensorflow

In [119]:
import tensorflow as tf
import numpy as np

# Tensor

Tensors are multi-dimensional arrays of numbers that represent complex data.

They are the fundamental data structures used in machine learning and deep learning frameworks like TensorFlow and PyTorch.

In other words creating an tensor is creating an matrix. 

In [120]:
# Creating a 0-dimensional tensor (a scalar)
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [121]:
# Creating a 1-dimensional tensor (a vector)
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [122]:
# Creating another 1-dimensional tensor (a vector with different elements)
tensor_one_d = tf.constant([2, 0, -3, 8, 90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [123]:
# Creating a 2-dimensional tensor (a matrix)
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [124]:
# Creating a 3-dimensional tensor
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [125]:
# Printing the shape of each tensor
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(4, 3)
(4, 2, 3)


In [126]:
# Printing the number of dimensions (rank) of tensors
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [127]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [128]:
# Finding the size (number of elements) in a tensor
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [129]:
# Finding the size in a specific dtype 
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [149]:
## Printing the shape and number of dimensions of a tensor
print(tf.shape(tensor_three_d))
print(tensor_three_d.ndim)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)
3


In [132]:
# Creating a 4-dimensional tensor
tensor_four_d = tf.constant([

[
    [[13,12,90],
    [33,57,-10]],

    [[10,2,0],
    [1,60,32]],

    [[85,18,0],
    [52,77,47]],

    [[52,81,69],
    [84,-3,32]]
],

[
    [[143,12,900],
    [303,527,-910]],

    [[150,2,440],
    [51,620,342]],

    [[85,186,103],
    [552,77,407]],

    [[52,181,69],
    [384,-3,632]]
],

[
    [[13,192,90],
    [33,57,-10]],

    [[10,2,0],
    [1,670,932]],

    [[865,18,0],
    [52,77,897]],

    [[542,81,69],
    [814,-63,432]]
]
])
print(tensor_four_d)

tf.Tensor(
[[[[  13   12   90]
   [  33   57  -10]]

  [[  10    2    0]
   [   1   60   32]]

  [[  85   18    0]
   [  52   77   47]]

  [[  52   81   69]
   [  84   -3   32]]]


 [[[ 143   12  900]
   [ 303  527 -910]]

  [[ 150    2  440]
   [  51  620  342]]

  [[  85  186  103]
   [ 552   77  407]]

  [[  52  181   69]
   [ 384   -3  632]]]


 [[[  13  192   90]
   [  33   57  -10]]

  [[  10    2    0]
   [   1  670  932]]

  [[ 865   18    0]
   [  52   77  897]]

  [[ 542   81   69]
   [ 814  -63  432]]]], shape=(3, 4, 2, 3), dtype=int32)


In [133]:
print(tensor_four_d.shape)

(3, 4, 2, 3)


In [134]:
# changing the dtype from float to integer
tensor_one_d = tf.constant([2, 0, -3, 8, 90.],dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [135]:
# Creating tensors with boolean and string data
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [136]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [150]:
# Converting a NumPy array into a TensorFlow tensor
np_array = np.array([1,2,4])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [139]:
# Creating special tensors which is 3x3 identity matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,    # batch dimensions od this shape
    dtype=tf.dtypes.float32,   # we can change dtype 
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [140]:
# Tensor filled with 5, shape (2, 3, 4)
fill_tensor = tf.fill(
    [2,3,4],5 ,name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [141]:
# Tensor filled with ones, shape (5, 3, 2)
ones_tensor = tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [142]:
# Tensor filled with zeros, shape (3, 2)
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [143]:
# Tensor of ones with the same shape as `fill_tensor`
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [144]:
# Creating random values tensors
random_tensor = tf.random.normal(
    [3, 2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-0.18030666 -0.95028627]
 [-0.03964049 -0.7425406 ]
 [ 1.3231523  -0.61854804]], shape=(3, 2), dtype=float32)


In [145]:
# Random values from a uniform distribution
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed =None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[97 64 60 58 70]
 [17 40 43 77 34]
 [32 29 83 64 94]
 [20 92 11 85 71]
 [ 1 94 50  6 33]], shape=(5, 5), dtype=int32)


In [146]:
# Setting a random seed for reproducibility
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


### Indexing and slicing tensors

In [147]:
# Indexing and slicing a 1D tensor
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])
print(tensor_indexed[1:6:2])
print(tensor_indexed[3:-2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [148]:
# Indexing and slicing a 2D tensor
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,7],
                            [9,1,4],
                            [4,7,5]])
print(tensor_two_d[0:3,0:2])
print(tensor_two_d[0:3,])
print(tensor_two_d[2,:])
print(tensor_two_d[2,1:])
print(tensor_two_d[:,0])
print(tensor_two_d[1:3,0])
print(tensor_two_d[...,1])

tf.Tensor(
[[1 2]
 [3 5]
 [9 1]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 0]
 [3 5 7]
 [9 1 4]], shape=(3, 3), dtype=int32)
tf.Tensor([9 1 4], shape=(3,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([1 3 9 4], shape=(4,), dtype=int32)
tf.Tensor([3 9], shape=(2,), dtype=int32)
tf.Tensor([2 5 1 7], shape=(4,), dtype=int32)


In [178]:
# Indexing and slicing a 3D tensor
tensor_three_d = tf.constant([
    [[ 2, 26, 61],
    [78, 71, 53]],

    [[ 3, 51, 94],
    [73, 80, 43]],

    [[ 4, 48, 96],
    [50, 93, 70]],

    [[37,  6, 19],
    [ 3, 42, 70]]
])
print(tensor_three_d[0, :, :])
print(tensor_three_d[0, 0, :])
print(tensor_three_d[0, :, -1])
print(tensor_three_d[0:2, :, 2])
print(tensor_three_d[0:2, ..., 2])
print(tensor_three_d[..., :, 2])

tf.Tensor(
[[ 2 26 61]
 [78 71 53]], shape=(2, 3), dtype=int32)
tf.Tensor([ 2 26 61], shape=(3,), dtype=int32)
tf.Tensor([61 53], shape=(2,), dtype=int32)
tf.Tensor(
[[61 53]
 [94 43]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[61 53]
 [94 43]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[61 53]
 [94 43]
 [96 70]
 [19 70]], shape=(4, 2), dtype=int32)
