In [178]:
import tensorflow as tf
import numpy as np

### Expanding dimension

In [179]:
d = tf.constant([[[1,2,3],
                  [4,5,6]],
                              
                  [[1,2,3],
                  [4,5,6]],

                  [[1,2,3],
                  [4,5,6]],
                              
                  [[1,2,3],
                  [4,5,6]]])

print(d.shape)
print(tf.expand_dims(d, axis = 0).shape)
print(tf.expand_dims(d, axis = 1).shape)
print(tf.expand_dims(d, axis = 2).shape)
print(tf.expand_dims(d, axis = 3).shape)

(4, 2, 3)
(1, 4, 2, 3)
(4, 1, 2, 3)
(4, 2, 1, 3)
(4, 2, 3, 1)


In [180]:
x =tf.constant([[2,3,4,5]])
print(x.shape)
print(tf.expand_dims(x, axis=0).shape)

(1, 4)
(1, 1, 4)


###  Remove the Dimensions

In [181]:
d = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 
                 [[1, 2, 3],
                  [4, 5, 6]],
                 
                 [[1, 2, 3],
                  [4, 5, 6]],
                 
                 [[1, 2, 3],
                  [4, 5, 6]]])

# Expand dimensions and print the shapes
print(d.shape)
print(tf.expand_dims(d, axis = 0).shape)
print(tf.expand_dims(d, axis = 1).shape)
print(tf.expand_dims(d, axis = 2).shape)
print(tf.expand_dims(d, axis = 3).shape)

# Squeeze the expanded tensors to remove the size-1 dimensions and print the shapes
print(tf.squeeze(tf.expand_dims(d, axis = 0)).shape)
print(tf.squeeze(tf.expand_dims(d, axis = 1)).shape)
print(tf.squeeze(tf.expand_dims(d, axis = 2)).shape)
print(tf.squeeze(tf.expand_dims(d, axis = 3)).shape)


(4, 2, 3)
(1, 4, 2, 3)
(4, 1, 2, 3)
(4, 2, 1, 3)
(4, 2, 3, 1)
(4, 2, 3)
(4, 2, 3)
(4, 2, 3)
(4, 2, 3)


### Reshape the Dimensions

In [182]:
d = tf.constant([[[1,2,3],
                  [4,5,6]],
                              
                  [[1,2,3],
                  [4,5,6]],

                  [[1,2,3],
                  [4,5,6]],
                              
                  [[1,2,3],
                  [4,5,6]]])

print(d.shape)  # original shape of the dimensions
print(tf.expand_dims(d, axis = 3).shape)  # expanded the shape of the dimensions
print(tf.reshape(d, [4,2,3]).shape) # reshapeing the dimensions

(4, 2, 3)
(4, 2, 3, 1)
(4, 2, 3)


In [183]:
x = tf.constant([[3,5,6,6],
                 [4,6,-1,2]])

a = tf.reshape(x, [8])
print(a)

b= tf.reshape(x, [4, 2])
print(b)

c = tf.reshape(x, [4, 2, 1])
print(c)

d = tf.reshape(x, [4, -1])
print(d)

e = tf.reshape(x, [-1])
print(e)

f = tf.reshape(x, [8])
print(f)

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)
tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[[ 3]
  [ 5]]

 [[ 6]
  [ 6]]

 [[ 4]
  [ 6]]

 [[-1]
  [ 2]]], shape=(4, 2, 1), dtype=int32)
tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32)
tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)
tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)


### CONCAT the tensor

In [184]:
t1 = tf.constant([[1, 2, 3],
                  [3, 4, 5]])

t2 = tf.constant([[5, 6, 7],
                  [7, 8, 9]])

# Concatenate along axis 0 (rows)
result = tf.concat([t1, t2], axis=0)

# Print the result
print("Concatenated Tensor along axis 0:")
print(result)

# Concatenate along axis 1 (columns)
result = tf.concat([t1, t2], axis=1)

# Print the result
print("Concatenated Tensor along axis 1:")
print(result)

Concatenated Tensor along axis 0:
tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]], shape=(4, 3), dtype=int32)
Concatenated Tensor along axis 1:
tf.Tensor(
[[1 2 3 5 6 7]
 [3 4 5 7 8 9]], shape=(2, 6), dtype=int32)


In [185]:
# Stack the tensors along a new axis 0
# or the tensor in its original form
tf.stack([t1,t2], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])>

In [186]:
# Define two 3D tensors
tensor3 = tf.constant([[[1, 2], [3, 4]],
                       [[5, 6], [7, 8]]])

tensor4 = tf.constant([[[9, 10], [11, 12]],
                       [[13, 14], [15, 16]]])

print(tensor3.shape)

# Concatenate along axis 2
result = tf.concat([tensor3, tensor4], axis=2)

# Print the result
print("Concatenated 3D Tensor along axis 2:")
print(result)

(2, 2, 2)
Concatenated 3D Tensor along axis 2:
tf.Tensor(
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]], shape=(2, 2, 4), dtype=int32)


### Padding to tensor

In [187]:
# Define a 2D tensor
t = tf.constant([[1, 2, 3],
                [4, 5, 6]])

# Define the padding: 1 row before and after, 2 columns before and after
paddings = tf.constant([[1, 1],
                        [2, 2]])

# Apply padding with constant value 0 (default)
# This adds zeros around the original tensor.
a = tf.pad(t, paddings, "CONSTANT")
print(a)

# Apply padding with a constant value of 3
# This adds the value 3 around the original tesor.
b = tf.pad(t, paddings, "CONSTANT", constant_values=3)
print(b)

# Apply reflective padding
# This pads the tensor by reflecting the values on the edge.
c = tf.pad(t, paddings, "REFLECT")
print(c)

# Apply symmetric padding
# This pads the tensor symmetrically, including the edge values in the reflection.
d = tf.pad(t, paddings, "SYMMETRIC")
print(d)


tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[3 3 3 3 3 3 3]
 [3 3 1 2 3 3 3]
 [3 3 4 5 6 3 3]
 [3 3 3 3 3 3 3]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)


### slices of tensor

In [188]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[3]

<tf.Tensor: shape=(), dtype=string, numpy=b'p3'>

In [189]:
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [190]:
tf.gather(params, [1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [191]:
tf.gather(params, [0,5,3], axis=0)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [192]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=[3,1])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[30., 31., 32.],
       [10., 11., 12.]], dtype=float32)>

In [193]:
tf.gather(params, [0], axis = 0)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 2.]], dtype=float32)>

In [194]:
tf.gather(params, [0,3], axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [30., 31., 32.]], dtype=float32)>

In [195]:
tf.gather(params, [2,1], axis=1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 2.,  1.],
       [12., 11.],
       [22., 21.],
       [32., 31.]], dtype=float32)>

In [196]:
tf.gather(params, [0,2], axis=1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.,  2.],
       [10., 12.],
       [20., 22.],
       [30., 32.]], dtype=float32)>

In [197]:
indices=[[0],
        [1]]

params = [['a', 'b'],
        ['c', 'd']]

# Use tf.gather_nd to extract the rows
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [198]:
indices=[[0]]

params = [['a', 'b'],
        ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'a', b'b']], dtype=object)>

In [199]:
indices=[[2,1]]

params = [['a', 'b'],
        ['c', 'd'],
        ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [200]:
indices = [[0, 1], [1, 0]],
params = [[['a0', 'b0'],
            ['c0', 'd0']],

        [['a1', 'b1'],
          ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']]], dtype=object)>

### Ragged Tensor

In [201]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])

print(tensor_two_d.shape)
print(tensor_two_d)

(4, 3)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [202]:
# Create a ragged tensor from a nested list with varying lengths
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [203]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


### SparseTensor

In [205]:
tensor_spare = tf.sparse.SparseTensor(
    indices=[[1, 1], [3, 4]], values=[11, 56], dense_shape=[5, 6])
print(tensor_spare)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [206]:
tf.sparse.to_dense(tensor_spare)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

### String Tensor

In [207]:
tensor_string = tf.constant(["hello", "i am", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [210]:
# join is use to join the string
tf.strings.join(tensor_string, separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

In [211]:
# length is use to get the length of the string
strings = tf.constant(['Hello','TensorFlow', '\U0001F642'])
tf.strings.length(strings)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10,  4])>

### variable

In [215]:
x = tf.constant([1, 2])

In [216]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [218]:
x_var.assign_sub([3,6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-5, -8])>

In [225]:
with tf.device('GPU:0'):
    x_var = tf.Variable(0.2)

with tf.device('CPU:0'):
    x_tensor = tf.Variable(0.2)

print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [229]:
with tf.device('CPU:0'):
    x_1 = tf.constant([1,3,4])
    x_2 = tf.constant([1])

with tf.device('GPU:0'):
    x_3 = x_1 + x_2
    
print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
