In [31]:
import tensorflow as tf
import numpy as np

### Absolute value


In [32]:
# This function did't convert your actual tensor to absolute value bhut it convert so you can use it in other verable or other function
# Your original variable remain unchanges
x_abs = tf.constant([-2.6,8.1])

tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.6, 8.1], dtype=float32)>

In [33]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [34]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

### Elementwise addition , division , substraction

In [35]:
# The shape and type of the tensor should be same for mathematical operations

x_1 = tf.constant([9,8,7,6,5])
x_2 = tf.constant([5,6,7,8,9])

add = print(tf.math.add(x_1,x_2))

sub = print(tf.math.subtract(x_1,x_2))

div = print(tf.math.divide(x_1,x_2))

print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([14 14 14 14 14], shape=(5,), dtype=int32)
tf.Tensor([ 4  2  0 -2 -4], shape=(5,), dtype=int32)
tf.Tensor([1.8        1.33333333 1.         0.75       0.55555556], shape=(5,), dtype=float64)
tf.Tensor([1.8        1.33333333 1.         0.75       0.55555556], shape=(5,), dtype=float64)


### Method is used to find the maximum value across the axes

In [36]:
# 1D tensor:

x_argmax = tf.constant([2,3,56,76,33])

print(x_argmax)

print(tf.math.argmax(x_argmax))   # this is the output shows the position of the max value

tf.Tensor([ 2  3 56 76 33], shape=(5,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int64)


In [37]:
# 2D tensor

y_argmax = tf.constant([[77,54,93],[14,55,60],[40,35,17]])

print(y_argmax)

print(tf.math.argmax(y_argmax,0)) # 0 is the rows 1 is the column axis  

# AXIS 0 vvvvvv (default) 

# AXIS 1 >>>>>

tf.Tensor(
[[77 54 93]
 [14 55 60]
 [40 35 17]], shape=(3, 3), dtype=int32)
tf.Tensor([0 1 0], shape=(3,), dtype=int64)


### Elementwise equal Checker

Returns the truth value of (x == y) element-wise.

Should be of same shape

In [38]:
X_equal = tf.constant([1,2,3,4])
Y_equal = tf.constant([1,2,3,4])

print(tf.math.equal(X_equal,Y_equal))

tf.Tensor([ True  True  True  True], shape=(4,), dtype=bool)


### The power of one value to another

In [39]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

### Reduce Sum

In [40]:
# Example Tensor (2D Tensor)
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Sum of all elements (axis=None)
total_sum = tf.reduce_sum(tensor, axis=None)
print("Sum of all elements:", total_sum)

# Sum along axis 0 (vertically across rows)
sum_axis_0 = tf.reduce_sum(tensor, axis=0)
print("Sum along axis 0 (vertical):", sum_axis_0)

# Sum along axis 1 (horizontally across columns)
sum_axis_1 = tf.reduce_sum(tensor, axis=1)
print("Sum along axis 1 (horizontal):", sum_axis_1)


Sum of all elements: tf.Tensor(45, shape=(), dtype=int32)
Sum along axis 0 (vertical): tf.Tensor([12 15 18], shape=(3,), dtype=int32)
Sum along axis 1 (horizontal): tf.Tensor([ 6 15 24], shape=(3,), dtype=int32)


In [41]:
y = tf.constant([[2,4,53],[4,5,6],[4,5,7]])
print(y)


print(tf.math.reduce_sum(
    y, axis=0, keepdims=False, name=None
))

tf.Tensor(
[[ 2  4 53]
 [ 4  5  6]
 [ 4  5  7]], shape=(3, 3), dtype=int32)
tf.Tensor([10 14 66], shape=(3,), dtype=int32)


### Reduce Mean

the mean of elements across dimensions of a tensor.

It Basically give mean on the basisi of axis

In [42]:
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Mean of all elements (axis=None)
mean_all = tf.reduce_mean(tensor, axis=None)
print("Mean of all elements:", mean_all)

# Mean along axis 0 (vertically across rows)
mean_axis_0 = tf.reduce_mean(tensor, axis=0)
print("Mean along axis 0 (vertical):", mean_axis_0)

# Mean along axis 1 (horizontally across columns)
mean_axis_1 = tf.reduce_mean(tensor, axis=1)
print("Mean along axis 1 (horizontal):", mean_axis_1)

Mean of all elements: tf.Tensor(5, shape=(), dtype=int32)
Mean along axis 0 (vertical): tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Mean along axis 1 (horizontal): tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [43]:
y = tf.constant([[2,4,53],[4,5,6],[4,5,7]])
print(y)


print(tf.math.reduce_sum(
    y, axis=0, keepdims=False, name=None
))

tf.Tensor(
[[ 2  4 53]
 [ 4  5  6]
 [ 4  5  7]], shape=(3, 3), dtype=int32)
tf.Tensor([10 14 66], shape=(3,), dtype=int32)


### Standard deviation

Computes the standard deviation of elements across dimensions of a tensor.

In [44]:
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=tf.float32)

# Standard deviation of all elements (axis=None)
std_all = tf.math.reduce_std(tensor, axis=None)
print("Standard deviation of all elements:", std_all)

# Standard deviation along axis 0 (vertically across rows)
std_axis_0 = tf.math.reduce_std(tensor, axis=0)
print("Standard deviation along axis 0 (vertical):", std_axis_0)

# Standard deviation along axis 1 (horizontally across columns)
std_axis_1 = tf.math.reduce_std(tensor, axis=1)
print("Standard deviation along axis 1 (horizontal):", std_axis_1)


Standard deviation of all elements: tf.Tensor(2.5819888, shape=(), dtype=float32)
Standard deviation along axis 0 (vertical): tf.Tensor([2.4494898 2.4494898 2.4494898], shape=(3,), dtype=float32)
Standard deviation along axis 1 (horizontal): tf.Tensor([0.8164966 0.8164966 0.8164966], shape=(3,), dtype=float32)


In [45]:
y = tf.constant([[2,4,53],[4,5,6],[4,5,7]],dtype=tf.float32)
print(y)

print(tf.math.reduce_std(
    y, axis=None, keepdims=False, name=None
))

tf.Tensor(
[[ 2.  4. 53.]
 [ 4.  5.  6.]
 [ 4.  5.  7.]], shape=(3, 3), dtype=float32)
tf.Tensor(15.260697, shape=(), dtype=float32)


### TOP Function

Finds values and indices of the k largest entries for the last dimension.

This function go to each and every Row and find top_k values

In [46]:
tensor = tf.constant([1, 3, 5, 7, 9, 2, 8, 6, 4, 0])

# Find the top 3 largest elements
top_k_values, top_k_indices = tf.math.top_k(tensor, k=3)

print("Top 3 values:", top_k_values)  # Output: [9 8 7]
print("Indices of top 3 values:", top_k_indices)  # Output: [4 6 3]


Top 3 values: tf.Tensor([9 8 7], shape=(3,), dtype=int32)
Indices of top 3 values: tf.Tensor([4 6 3], shape=(3,), dtype=int32)


In [47]:
# The second array in the output is the index of the top k value

y = tf.constant([[2,4,53],[4,5,6],[4,5,7]],dtype=tf.float32)
print(y)

print(tf.math.top_k(
    y,
    k=1,
    sorted=True,
    index_type=tf.dtypes.int32,
    name=None
))


tf.Tensor(
[[ 2.  4. 53.]
 [ 4.  5.  6.]
 [ 4.  5.  7.]], shape=(3, 3), dtype=float32)
TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[53.],
       [ 6.],
       [ 7.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]])>)
